var textData={
   "expanded":[
      [
         [
            "NOUN",
            "University"
         ],
         [
            "NOUN",
            "ice"
         ],
         [
            "NOUN",
            "hockey"
         ],
         [
            "NOUN",
            "gymnastic"
         ],
         [
            "NOUN",
            "game"
         ],
         [
            "NOUN",
            "footage"
         ],
         [
            "NOUN",
            "student"
         ],
         [
            "NOUN",
            "athlete"
         ],
         [
            "NOUN",
            "fan"
         ],
         [
            "NOUN",
            "Crane"
         ],
         [
            "NOUN",
            "Jenkins"
         ],
         [
            "NOUN",
            "Graduate"
         ],
         [
            "NOUN",
            "Assistant"
         ],
         [
            "NOUN",
            "position"
         ],
         [
            "NOUN",
            "department"
         ],
         [
            "NOUN",
            "day"
         ],
         [
            "NOUN",
            "Marketing"
         ],
         [
            "NOUN",
            "team"
         ],
         [
            "NOUN",
            "experience"
         ],
         [
            "NOUN",
            "goal"
         ]
      ],
      [
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1
      ],
      [
         [
            "NOUN",
            "University",
            "University",
            false,
            "conj",
            "univers",
            null,
            false,
            1,
            1,
            true,
            false,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "Crane",
            "Crane",
            false,
            "pobj",
            "crane",
            null,
            false,
            1,
            1,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "Jenkins",
            "Jenkins",
            false,
            "compound",
            "jenkin",
            null,
            false,
            1,
            1,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "Graduate",
            "Graduate",
            false,
            "compound",
            "graduat",
            null,
            false,
            1,
            1,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "Assistant",
            "Assistant",
            false,
            "compound",
            "assist",
            null,
            false,
            1,
            1,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "position",
            "position",
            false,
            "pobj",
            "posit",
            null,
            false,
            1,
            1,
            true,
            false,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ]
      ],
      [
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "student",
            "student",
            true,
            "pobj",
            "student",
            null,
            false,
            1,
            2,
            true,
            false,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "position",
            "position",
            false,
            "dobj",
            "posit",
            null,
            false,
            1,
            2,
            true,
            false,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ]
      ],
      [
         [
            null,
            false
         ],
         [
            "NOUN",
            "ice",
            "ice",
            false,
            "compound",
            "ice",
            null,
            false,
            1,
            3,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "hockey",
            "hockey",
            false,
            "pobj",
            "hockey",
            null,
            false,
            1,
            3,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "gymnastics",
            "gymnastic",
            false,
            "conj",
            "gymnast",
            null,
            false,
            1,
            3,
            true,
            false,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ]
      ],
      [
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "game",
            "game",
            false,
            "compound",
            "game",
            null,
            false,
            1,
            4,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "footage",
            "footage",
            false,
            "dobj",
            "footag",
            null,
            false,
            1,
            4,
            true,
            false,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ]
      ],
      [
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "student",
            "student",
            false,
            "compound",
            "student",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "athletes",
            "athlete",
            false,
            "conj",
            "athlet",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "conj",
            "fan",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ]
      ],
      [
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1
      ],
      [
         [
            "NOUN",
            "University",
            "University",
            true,
            "pobj",
            "univers",
            null,
            false,
            2,
            1,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "ice",
            "ice",
            false,
            "compound",
            "ice",
            null,
            false,
            2,
            1,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "hockey",
            "hockey",
            false,
            "conj",
            "hockey",
            null,
            false,
            2,
            1,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "gymnastics",
            "gymnastic",
            false,
            "compound",
            "gymnast",
            null,
            false,
            2,
            1,
            false,
            true,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "Marketing",
            "Marketing",
            false,
            "compound",
            "market",
            null,
            false,
            2,
            1,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "teams",
            "team",
            false,
            "conj",
            "team",
            null,
            false,
            2,
            1,
            true,
            false,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ]
      ],
      [
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "game",
            "game",
            false,
            "compound",
            "game",
            null,
            false,
            2,
            2,
            true,
            true,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "day",
            "day",
            false,
            "compound",
            "day",
            null,
            false,
            2,
            2,
            true,
            false,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ]
      ],
      [
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "game",
            "game",
            false,
            "compound",
            "game",
            null,
            false,
            2,
            3,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "footage",
            "footage",
            false,
            "dobj",
            "footag",
            null,
            false,
            2,
            3,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "student",
            "student",
            false,
            "compound",
            "student",
            null,
            false,
            2,
            3,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "athletes",
            "athlete",
            false,
            "dobj",
            "athlet",
            null,
            false,
            2,
            3,
            false,
            true,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "day",
            "day",
            false,
            "compound",
            "day",
            null,
            false,
            2,
            3,
            true,
            false,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ]
      ],
      [
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "athletes",
            "athlete",
            false,
            "conj",
            "athlet",
            null,
            false,
            2,
            4,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ]
      ],
      [
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1
      ],
      [
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "games",
            "game",
            false,
            "pobj",
            "game",
            null,
            false,
            3,
            1,
            false,
            true,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "dobj",
            "fan",
            null,
            false,
            3,
            1,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "Crane",
            "Crane",
            true,
            "nmod",
            "crane",
            null,
            false,
            3,
            1,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "Jenkins",
            "Jenkins",
            true,
            "conj",
            "jenkin",
            null,
            false,
            3,
            1,
            true,
            true,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ]
      ],
      [
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "game",
            "game",
            false,
            "compound",
            "game",
            null,
            false,
            3,
            2,
            false,
            true,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "experience",
            "experience",
            false,
            "dobj",
            "experi",
            null,
            false,
            3,
            2,
            true,
            false,
            false
         ],
         [
            null,
            false
         ]
      ],
      [
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "game",
            "game",
            false,
            "compound",
            "game",
            null,
            false,
            3,
            3,
            false,
            true,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "days",
            "day",
            false,
            "pobj",
            "day",
            null,
            false,
            3,
            3,
            false,
            true,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ]
      ],
      [
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "hockey",
            "hockey",
            true,
            "compound",
            "hockey",
            null,
            false,
            3,
            4,
            false,
            true,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "game",
            "game",
            true,
            "pobj",
            "game",
            null,
            false,
            3,
            4,
            false,
            true,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "student",
            "student",
            true,
            "compound",
            "student",
            null,
            false,
            3,
            4,
            false,
            true,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            true,
            "pobj",
            "goal",
            null,
            false,
            3,
            4,
            true,
            false,
            false
         ]
      ],
      [
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ]
      ],
      [
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1
      ],
      [
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ]
      ],
      [
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ]
      ],
      [
         [
            "NOUN",
            "University",
            "University",
            false,
            "conj",
            "univers",
            null,
            false,
            4,
            3,
            false,
            true,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "Crane",
            "Crane",
            false,
            "pobj",
            "crane",
            null,
            false,
            4,
            3,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "Jenkins",
            "Jenkins",
            false,
            "compound",
            "jenkin",
            null,
            false,
            4,
            3,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "Graduate",
            "Graduate",
            false,
            "compound",
            "graduat",
            null,
            false,
            4,
            3,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "Assistant",
            "Assistant",
            false,
            "compound",
            "assist",
            null,
            false,
            4,
            3,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "position",
            "position",
            false,
            "pobj",
            "posit",
            null,
            false,
            4,
            3,
            false,
            true,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ]
      ],
      [
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "position",
            "position",
            false,
            "nsubj",
            "posit",
            null,
            false,
            4,
            4,
            false,
            true,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ]
      ],
      [
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "department",
            "department",
            true,
            "pobj",
            "depart",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ],
         [
            null,
            false
         ],
         [
            "NOUN",
            "Marketing",
            "Marketing",
            false,
            "compound",
            "market",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "team",
            "team",
            false,
            "pobj",
            "team",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "experience",
            "experience",
            true,
            "dobj",
            "experi",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1,
         -1
      ]
   ],
   "collapsed":[
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ],
      [
         [
            [
               "NOUN",
               "University"
            ],
            [
               "NOUN",
               "ice"
            ],
            [
               "NOUN",
               "hockey"
            ],
            [
               "NOUN",
               "gymnastic"
            ],
            [
               "NOUN",
               "game"
            ],
            [
               "NOUN",
               "footage"
            ],
            [
               "NOUN",
               "student"
            ],
            [
               "NOUN",
               "athlete"
            ],
            [
               "NOUN",
               "fan"
            ],
            [
               "NOUN",
               "Crane"
            ],
            [
               "NOUN",
               "Jenkins"
            ],
            [
               "NOUN",
               "Graduate"
            ],
            [
               "NOUN",
               "Assistant"
            ],
            [
               "NOUN",
               "position"
            ],
            [
               "NOUN",
               "department"
            ],
            [
               "NOUN",
               "day"
            ],
            [
               "NOUN",
               "Marketing"
            ],
            [
               "NOUN",
               "team"
            ],
            [
               "NOUN",
               "experience"
            ],
            [
               "NOUN",
               "goal"
            ]
         ],
         [
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
         ],
         [
            "NOUN",
            "department",
            "department",
            false,
            "dobj",
            "depart",
            null,
            false,
            1,
            5,
            true,
            false,
            false
         ],
         [
            "NOUN",
            "fans",
            "fan",
            false,
            "pobj",
            "fan",
            null,
            false,
            2,
            4,
            true,
            true,
            false
         ],
         [
            "NOUN",
            "students",
            "student",
            true,
            "nsubj",
            "student",
            null,
            false,
            3,
            5,
            false,
            true,
            false
         ],
         [
            "NOUN",
            "goal",
            "goal",
            false,
            "pobj",
            "goal",
            null,
            false,
            4,
            5,
            false,
            true,
            false
         ]
      ]
   ]
};

export { textData };
